function out1 = v_opt(t,v0,a0,sf,vf,af,tf)
%V_OPT
%    OUT1 = V_OPT(T,V0,A0,SF,VF,AF,TF)

%    This function was generated by the Symbolic Math Toolbox version 26.2.
%    08-Oct-2026 12:10:41

t2 = tf.^2;
t3 = af.*t2;
t4 = a0.*t2.*3.0;
t5 = -t3;
out1 = v0+a0.*t+t.^3.*1.0./t2.^2.*(sf.*-3.0e+1-t3.*2.0+t4+tf.*v0.*1.6e+1+tf.*vf.*1.4e+1).*2.0-t.^4.*1.0./tf.^5.*(sf.*-1.2e+1+t5+a0.*t2+tf.*v0.*6.0+tf.*vf.*6.0).*(5.0./2.0)-t.^2.*1.0./tf.^3.*(sf.*-2.0e+1+t4+t5+tf.*v0.*1.2e+1+tf.*vf.*8.0).*(3.0./2.0);
end
